-- MySQL Script generated by MySQL Workbench
-- Fri Jun  7 06:47:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema clubnautico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clubnautico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clubnautico` DEFAULT CHARACTER SET utf8 ;
USE `clubnautico` ;

-- -----------------------------------------------------
-- Table `clubnautico`.`socio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clubnautico`.`socio` ;

CREATE TABLE IF NOT EXISTS `clubnautico`.`socio` (
  `idsocio` INT NOT NULL,
  `dni` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idsocio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clubnautico`.`patron`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clubnautico`.`patron` ;

CREATE TABLE IF NOT EXISTS `clubnautico`.`patron` (
  `licenciatura` INT NULL,
  `idpatron` INT NOT NULL,
  PRIMARY KEY (`idpatron`),
  INDEX `fk_patron_socio1_idx` (`idpatron` ASC) VISIBLE,
  CONSTRAINT `fk_patron_socio1`
    FOREIGN KEY (`idpatron`)
    REFERENCES `clubnautico`.`socio` (`idsocio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clubnautico`.`barco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clubnautico`.`barco` ;

CREATE TABLE IF NOT EXISTS `clubnautico`.`barco` (
  `idbarco` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `matricula` VARCHAR(45) NULL,
  `cuota` DOUBLE NULL,
  `socio_idsocio` INT NOT NULL,
  `patron_idpatron` INT NOT NULL,
  PRIMARY KEY (`idbarco`),
  INDEX `fk_barco_socio1_idx` (`socio_idsocio` ASC) VISIBLE,
  INDEX `fk_barco_patron1_idx` (`patron_idpatron` ASC) VISIBLE,
  CONSTRAINT `fk_barco_socio1`
    FOREIGN KEY (`socio_idsocio`)
    REFERENCES `clubnautico`.`socio` (`idsocio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_barco_patron1`
    FOREIGN KEY (`patron_idpatron`)
    REFERENCES `clubnautico`.`patron` (`idpatron`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clubnautico`.`salida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clubnautico`.`salida` ;

CREATE TABLE IF NOT EXISTS `clubnautico`.`salida` (
  `idsalida` INT NOT NULL,
  `fecha` DATE NULL,
  `barco_idbarco` INT NOT NULL,
  `patron_idpatron` INT NOT NULL,
  PRIMARY KEY (`idsalida`),
  INDEX `fk_salida_barco_idx` (`barco_idbarco` ASC) VISIBLE,
  INDEX `fk_salida_patron1_idx` (`patron_idpatron` ASC) VISIBLE,
  CONSTRAINT `fk_salida_barco`
    FOREIGN KEY (`barco_idbarco`)
    REFERENCES `clubnautico`.`barco` (`idbarco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_salida_patron1`
    FOREIGN KEY (`patron_idpatron`)
    REFERENCES `clubnautico`.`patron` (`idpatron`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;